'use client'

import { useState, useEffect } from 'react'
import { useParams } from 'next/navigation'
import ItineraryDisplay from '../../components/ItineraryDisplay'
import { MapPin, Calendar, Clock, Users } from 'lucide-react'

interface SharedTripData {
  share_id: string
  session_id: string
  title: string
  destination: string
  itinerary: any
  created_at: string
  view_count: number
}

export default function SharedTripPage() {
  const params = useParams()
  const shareId = params.shareId as string
  
  const [tripData, setTripData] = useState<SharedTripData | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    const fetchSharedTrip = async () => {
      try {
        const API_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000'
        const response = await fetch(`${API_URL}/api/shared/${shareId}`)
        
        if (!response.ok) {
          if (response.status === 404) {
            throw new Error('This shared trip was not found or has expired.')
          }
          throw new Error('Failed to load shared trip')
        }
        
        const data = await response.json()
        setTripData(data)
      } catch (err) {
        setError(err instanceof Error ? err.message : 'An error occurred')
      } finally {
        setLoading(false)
      }
    }

    if (shareId) {
      fetchSharedTrip()
    }
  }, [shareId])

  if (loading) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600 mx-auto"></div>
          <p className="mt-4 text-gray-600">Loading shared trip...</p>
        </div>
      </div>
    )
  }

  if (error || !tripData) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="text-center max-w-md mx-auto p-6">
          <div className="w-16 h-16 bg-red-100 rounded-full flex items-center justify-center mx-auto mb-4">
            <MapPin className="h-8 w-8 text-red-600" />
          </div>
          <h1 className="text-2xl font-bold text-gray-900 mb-2">Trip Not Found</h1>
          <p className="text-gray-600 mb-6">
            {error || 'This shared trip could not be found or may have expired.'}
          </p>
          <a 
            href="/"
            className="inline-flex items-center px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors"
          >
            <MapPin className="h-4 w-4 mr-2" />
            Plan Your Own Trip
          </a>
        </div>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <header className="bg-white border-b shadow-sm">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center">
              <a href="/" className="flex items-center space-x-2">
                <div className="w-8 h-8 bg-gradient-to-r from-blue-600 to-purple-600 rounded-lg flex items-center justify-center">
                  <MapPin className="h-5 w-5 text-white" />
                </div>
                <span className="text-xl font-bold text-gray-900">AI Trip Planner</span>
              </a>
            </div>
            
            <div className="flex items-center space-x-4 text-sm text-gray-600">
              <div className="flex items-center">
                <Users className="h-4 w-4 mr-1" />
                <span>{tripData.view_count} views</span>
              </div>
              <div className="flex items-center">
                <Clock className="h-4 w-4 mr-1" />
                <span>Shared {new Date(tripData.created_at).toLocaleDateString()}</span>
              </div>
            </div>
          </div>
        </div>
      </header>

      {/* Shared Trip Banner */}
      <div className="bg-gradient-to-r from-blue-50 to-purple-50 border-b">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6">
          <div className="text-center">
            <h1 className="text-3xl font-bold text-gray-900 mb-2">
              {tripData.title}
            </h1>
            <p className="text-lg text-gray-600 flex items-center justify-center">
              <MapPin className="h-5 w-5 mr-2" />
              Shared Trip to {tripData.destination}
            </p>
            <div className="mt-4 inline-flex items-center px-4 py-2 bg-blue-100 text-blue-800 rounded-full text-sm font-medium">
              ✨ Generated by AI Trip Planner
            </div>
          </div>
        </div>
      </div>

      {/* Trip Content */}
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {tripData.itinerary ? (
          <ItineraryDisplay 
            itinerary={tripData.itinerary} 
            sessionId={null} // Shared trips can't be saved/reshared
          />
        ) : (
          <div className="text-center py-12">
            <p className="text-gray-600">No itinerary data available for this shared trip.</p>
          </div>
        )}
      </div>

      {/* CTA Section */}
      <div className="bg-white border-t mt-16">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12 text-center">
          <h3 className="text-2xl font-bold text-gray-900 mb-4">
            Want to create your own AI-powered trip?
          </h3>
          <p className="text-lg text-gray-600 mb-8 max-w-2xl mx-auto">
            Our AI agents can create personalized itineraries for any destination based on your preferences, budget, and travel style.
          </p>
          <a 
            href="/"
            className="inline-flex items-center px-6 py-3 bg-gradient-to-r from-blue-600 to-purple-600 text-white font-semibold rounded-lg hover:from-blue-700 hover:to-purple-700 transition-all duration-200 shadow-lg hover:shadow-xl"
          >
            <MapPin className="h-5 w-5 mr-2" />
            Plan My Trip with AI
          </a>
        </div>
      </div>

      {/* Footer */}
      <footer className="bg-gray-800 text-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 text-center">
          <p>© 2024 AI Trip Planner. Powered by advanced AI agents and LangChain.</p>
        </div>
      </footer>
    </div>
  )
}
